server:
  port: 80

spring:
  application:
    name: concul-customer-order
  #热部署生效
  devtools:
    restart:
      enabled: true
  #consul注册中心地址
  cloud:
    consul:
      host: 192.168.190.132
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        #开启ip地址
        prefer-ip-address: true
        #consul健康检查
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
