server:
  port: 9004


spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb2020?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    password: username
    username: root
  #热部署生效
  devtools:
    restart:
      enabled: true
  cloud:
    zookeeper:
      connect-string: 192.168.190.132:2181
