server:
  port: 9001

#配置spring application 名称
spring:
  application:
    name: cloud-provider-hystrix-payment9001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb2020?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    password: username
    username: root
#注册eureka
eureka:
  client:
    register-with-eureka: true  #向eureka中注册自己
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      instance:
        #instance-id: hytrix-payment9001  #修改服务名称
        prefer-ip-address: true  #显示ip
